sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
script: |
  cargo build &&
  cargo test #&&
  # cargo doc
  
notifications:
  email:
    on_success: never